"use client";
import { useState, useEffect } from "react";
import React from "react";
import "./globals.css";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  const [cart, setCart] = useState({});
  const [subtotal, setsubtotal] = useState();

  const saveCart = (myCart) => {
    localStorage.setItem("cart", myCart);
  };

  const addToCart = (itemCode, qty, name, price, size, varriant) => {
    let newCart = cart;
    if (itemCode in cart) {
      newCart[itemCode].qty = cart[itemCode].qty + 1;
    } else {
      newCart[itemCode] = { qty: 1, price, name, size, varriant };
    }
    setCart(newCart);
    saveCart(newCart);
  };

  const clearCart = () => {
    setCart({});
    saveCart({});
  };

  const removeFromCart = (itemCode, qty, name, price, size, varriant) => {
    let newCart = cart;
    if (itemCode in cart) {
      newCart[itemCode].qty = cart[itemCode].qty - qty;
    }
    if (newCart[itemCode]["qty"] <= 0) {
      delete newCart[itemCode];
    }
    setCart(newCart);
    saveCart(newCart);
  };

  const metadata = {
    title: "CodeSwear.com - Wear The Code",
    description: "Generated by create next app",
  };

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
