"use client"
import { useState } from 'react';
import React, { useEffect } from "react";
import "./globals.css";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const [cart, setCart] = useState({})
const [subtotal, setsubtotal] = useState(second)
const saveCart = (myCart) => {
  localStorage.setItem('cart', myCart)
}

const addToCart = (itemCode, qty, name, price, size, varriant)=>{
  let newCart = cart;
  if(itemCode in cart){
    newCart[itemCode] .qty = cart [itemCode].qty + 1 
  }else{
    newCart[itemCode]= {qty: 1, price, name, size, varriant }
  }
  setCart(newCart)
  saveCart(newCart)
}
const clearCart = () => {
  setCart({})
  saveCart({})
}
const removeFromCart = (itemCode, qty, name, price, size, varriant)=>{
  let newCart = cart;
  if(itemCode in cart){
    newCart[itemCode] .qty = cart [itemCode].qty - qty
  }
  if(newCart[itemCode]['qty']<=0){
    delete newCart[itemCode]
  }
  setCart(newCart)
  saveCart(newCart)
}

const metadata = {
  title: "CodeSwear.com - Wear The Code",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
